# Случайное блуждание

__Автор задач: Блохин Н.В. (NVBlokhin@fa.ru)__

Материалы:
* Макрушин С.В. "Лекция 5: Случайные блуждания на графах"
* Документация:
    * https://networkx.org/documentation/stable/reference/generated/networkx.generators.social.karate_club_graph.html
    * https://numpy.org/doc/stable/reference/generated/numpy.diag.html
    * https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html
    * https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_power.html
    * https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

## Вопросы для совместного обсуждения

1\. Обсудите понятие случайного блуждания на графах.

In [ ]:
import networkx as nx

In [ ]:
G = nx.karate_club_graph()

In [ ]:
G.edges(data="weight")

In [ ]:
A = nx.adjacency_matrix(G, weight=None).toarray()
A

array([[0, 1, 1, ..., 1, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 1, 1, 0]])

In [ ]:
A[0] / A[0].sum()

array([0.    , 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625,
       0.0625, 0.    , 0.0625, 0.0625, 0.0625, 0.0625, 0.    , 0.    ,
       0.    , 0.0625, 0.    , 0.0625, 0.    , 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.0625,
       0.    , 0.    ])

In [ ]:
import numpy as np

D = np.diag([1, 2, 3, 4])
D

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Задачи для самостоятельного решения

<p class="task" id="1"></p>

1\. Загрузите граф карате-клуба. Получите матрицу смежности `A` этого графа. Получите на ее основе матрицу переходов `P` по следующему правилу:

$$\mathbf{P}=\mathbf{D}^{-1}\mathbf{A}$$

Продемонстрируйте, что выполняются условия (1) и (2).

$0 \le p_{ij} \le 1$ (1)

$\sum_j p_{ij}=1$    (2)

- [ ] Проверено на семинаре

In [53]:
import networkx as nx
import numpy as np

In [54]:
graph = nx.karate_club_graph()
A = nx.adjacency_matrix(graph).toarray()
A

array([[0, 4, 5, ..., 2, 0, 0],
       [4, 0, 6, ..., 0, 0, 0],
       [5, 6, 0, ..., 0, 2, 0],
       ...,
       [2, 0, 0, ..., 0, 4, 4],
       [0, 0, 2, ..., 4, 0, 5],
       [0, 0, 0, ..., 4, 5, 0]])

In [55]:
D = np.diag(np.sum(A, axis=1))
P = np.dot(np.linalg.inv(D), A)
P

array([[0.        , 0.0952381 , 0.11904762, ..., 0.04761905, 0.        ,
        0.        ],
       [0.13793103, 0.        , 0.20689655, ..., 0.        , 0.        ,
        0.        ],
       [0.15151515, 0.18181818, 0.        , ..., 0.        , 0.06060606,
        0.        ],
       ...,
       [0.0952381 , 0.        , 0.        , ..., 0.        , 0.19047619,
        0.19047619],
       [0.        , 0.        , 0.05263158, ..., 0.10526316, 0.        ,
        0.13157895],
       [0.        , 0.        , 0.        , ..., 0.08333333, 0.10416667,
        0.        ]])

In [56]:
condition_1 = np.all((P >= 0) & (P <= 1))
condition_1

True

In [57]:
sum_columns = np.sum(P, axis=1)
condition_2 = np.allclose(sum_columns, 1)
condition_2

True

<p class="task" id="2"></p>

2\. Создайте вектор начального состояния $\mathbf{p}^0 = [0, ..., 1]^T$. Получите стационарное состояние $\mathbf{p}^\infty$, используя итеративную процедуру

$\mathbf{p}^{t+1}=(\mathbf{P}^{\top})\mathbf{p}^t$

Процесс заканчивается, когда $||\mathbf{p}^{t+1} - \mathbf{p}^{t}|| < \epsilon $

Выведите полученный вектор стационарного состояния на экран.

- [ ] Проверено на семинаре

In [64]:
p0 = np.zeros((len(graph),1))
p0[-1] = 1
p0

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.]])

In [65]:
k=0
for i in range(1,1000):
  k+=1
  p_new = np.dot(P.T,p0)
  if np.linalg.norm(p_new - p0) < 1e-6:
    break
  p0 = p_new
print(f'Кол-во итераций: {k}')
p_new

Кол-во итераций: 86


array([[0.09090599],
       [0.06276931],
       [0.07142793],
       [0.03896009],
       [0.01731493],
       [0.03030081],
       [0.02813649],
       [0.0281379 ],
       [0.03679691],
       [0.00649362],
       [0.01731486],
       [0.00649326],
       [0.00865775],
       [0.03679601],
       [0.01082289],
       [0.01515203],
       [0.01298595],
       [0.00649329],
       [0.00649372],
       [0.01082232],
       [0.00865831],
       [0.00865775],
       [0.01082288],
       [0.04545627],
       [0.01515207],
       [0.03030417],
       [0.01298754],
       [0.0281394 ],
       [0.01298725],
       [0.02813965],
       [0.02380994],
       [0.04545588],
       [0.08225373],
       [0.1038991 ]])

<p class="task" id="3"></p>

3\. Найдите матрицу перехода к стационарному состоянию $(\mathbf{P}^{\top})^\infty$ при помощи процедуры возведения матрицы в степень.

Докажите, что полученная матрица является матрицей стационарного состояния, т.е. $||(\mathbf{P}^{\top})^{\infty}  -(\mathbf{P}^{\top})(\mathbf{P}^{\top})^{\infty}|| <= \epsilon$

Выведите полученную матрицу на экран.

- [ ] Проверено на семинаре

In [66]:
P_stationary = np.linalg.matrix_power(P.T, 1000)  # Возведение в большую степень

norm_diff = np.linalg.norm(P_stationary - np.dot(P.T, P_stationary))
condition = norm_diff <= 1e-6

print(P_stationary)
print("Условие выполняется:", condition)

[[0.09090909 0.09090909 0.09090909 ... 0.09090909 0.09090909 0.09090909]
 [0.06277056 0.06277056 0.06277056 ... 0.06277056 0.06277056 0.06277056]
 [0.07142857 0.07142857 0.07142857 ... 0.07142857 0.07142857 0.07142857]
 ...
 [0.04545455 0.04545455 0.04545455 ... 0.04545455 0.04545455 0.04545455]
 [0.08225108 0.08225108 0.08225108 ... 0.08225108 0.08225108 0.08225108]
 [0.1038961  0.1038961  0.1038961  ... 0.1038961  0.1038961  0.1038961 ]]
Условие выполняется: True


<p class="task" id="4"></p>

4\. Cоздайте вектор начального состояния $\mathbf{p}^0 = [0, ..., 1]^T $. Получите стационарное состояние $\mathbf{p}^\infty$, воспользовавшись полученной матрицей $(\mathbf{P}^{\top})^\infty$. Решите задачу двумя способами: при помощи матричного умножения и при помощи оператора индексации.

Используя функцию `np.allclose`, покажите, что векторы стационарных состояний, полученные двумя разными методами, совпадают (с точностью до тысячных).

- [ ] Проверено на семинаре

In [75]:
#1 способ
p0 = np.zeros((len(graph),1))
p0[-1] = 1
p0

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.]])

In [76]:
P_1 = np.dot(P_stationary,p0)
P_1

array([[0.09090909],
       [0.06277056],
       [0.07142857],
       [0.03896104],
       [0.01731602],
       [0.03030303],
       [0.02813853],
       [0.02813853],
       [0.03679654],
       [0.00649351],
       [0.01731602],
       [0.00649351],
       [0.00865801],
       [0.03679654],
       [0.01082251],
       [0.01515152],
       [0.01298701],
       [0.00649351],
       [0.00649351],
       [0.01082251],
       [0.00865801],
       [0.00865801],
       [0.01082251],
       [0.04545455],
       [0.01515152],
       [0.03030303],
       [0.01298701],
       [0.02813853],
       [0.01298701],
       [0.02813853],
       [0.02380952],
       [0.04545455],
       [0.08225108],
       [0.1038961 ]])

In [77]:
P_stationary

array([[0.09090909, 0.09090909, 0.09090909, ..., 0.09090909, 0.09090909,
        0.09090909],
       [0.06277056, 0.06277056, 0.06277056, ..., 0.06277056, 0.06277056,
        0.06277056],
       [0.07142857, 0.07142857, 0.07142857, ..., 0.07142857, 0.07142857,
        0.07142857],
       ...,
       [0.04545455, 0.04545455, 0.04545455, ..., 0.04545455, 0.04545455,
        0.04545455],
       [0.08225108, 0.08225108, 0.08225108, ..., 0.08225108, 0.08225108,
        0.08225108],
       [0.1038961 , 0.1038961 , 0.1038961 , ..., 0.1038961 , 0.1038961 ,
        0.1038961 ]])

In [78]:
#2 способ
P_2 = P_stationary[:,-1]
P_2

array([0.09090909, 0.06277056, 0.07142857, 0.03896104, 0.01731602,
       0.03030303, 0.02813853, 0.02813853, 0.03679654, 0.00649351,
       0.01731602, 0.00649351, 0.00865801, 0.03679654, 0.01082251,
       0.01515152, 0.01298701, 0.00649351, 0.00649351, 0.01082251,
       0.00865801, 0.00865801, 0.01082251, 0.04545455, 0.01515152,
       0.03030303, 0.01298701, 0.02813853, 0.01298701, 0.02813853,
       0.02380952, 0.04545455, 0.08225108, 0.1038961 ])

In [79]:
P_2 = np.reshape(P_2,(-1,1))
P_2

array([[0.09090909],
       [0.06277056],
       [0.07142857],
       [0.03896104],
       [0.01731602],
       [0.03030303],
       [0.02813853],
       [0.02813853],
       [0.03679654],
       [0.00649351],
       [0.01731602],
       [0.00649351],
       [0.00865801],
       [0.03679654],
       [0.01082251],
       [0.01515152],
       [0.01298701],
       [0.00649351],
       [0.00649351],
       [0.01082251],
       [0.00865801],
       [0.00865801],
       [0.01082251],
       [0.04545455],
       [0.01515152],
       [0.03030303],
       [0.01298701],
       [0.02813853],
       [0.01298701],
       [0.02813853],
       [0.02380952],
       [0.04545455],
       [0.08225108],
       [0.1038961 ]])

In [80]:
#Проверка
np.allclose(P_1,P_2)

True

<p class="task" id="5"></p>

5\. Напишите функцию `generate_walk`, которая принимает на вход граф `G`, начальный узел `node` и генерирует случайное блуждание длины `walk_len`, начинающееся с этого узла. Сгенерируйте несколько реализаций (не меньше 1000) случайных блужданий длины 10 с началом в узле 7 и выясните, в каком узле случайные блуждания заканчиваются чаще всего. Выведите номер этого узла на экран.

- [ ] Проверено на семинаре

In [ ]:
def generate_walk(G, node, walk_len):
    # ...
    return walk